// let para1 = "It was a quiet Sunday afternoon, and the sun peeked through the curtains just enough to light up the cozy little room. A warm cup of coffee sat beside an open book, pages slightly curled from use. Outside, birds chirped lazily, and the soft rustling of leaves added a gentle rhythm to the air. Emma sat by the window, lost in thought, remembering her last trip to the mountains. The fresh air, the sound of rushing streams, and the smell of pine trees still lingered in her memory. She smiled at the thought of waking up to the sunrise over snow-covered peaks. Back in the present, her cat hopped onto her lap and purred softly, reminding her that even the smallest moments could bring peace. Maybe, she thought, she didn’t need to travel far to find joy. Sometimes, it was right here, in the stillness of home, with a warm drink, a good memory, and a furry companion by her side. The rain had been falling steadily all morning, tapping gently against the windows like a calm lullaby. Inside, the house smelled of cinnamon and fresh-baked cookies, thanks to an early burst of baking inspiration. The soft hum of music played in the background while Alex curled up on the couch with a blanket and a favorite movie queued up. Outside, the street looked like a watercolor painting, with reflections shimmering on the wet pavement and people walking by with colorful umbrellas. Even the trees looked more alive, their leaves glistening with droplets. Alex glanced at the to-do list on the fridge and smiled, knowing none of it needed attention today. Sometimes the best kind of productivity was simply taking a break. With a sip of hot chocolate and the sound of rain as a soundtrack, the world felt softer, quieter, and just right."

export const para1 = {
    l1: "It was a quiet Sunday afternoon, and the sun peeked through ",
    l2: "the curtains just enough to light up the cozy little room.",
    l3: "A warm cup of coffee sat beside an open book, pages slightly ",
    l4: "curled from use. Outside, birds chirped lazily, and the soft ",
    l5: "rustling of leaves added a gentle rhythm to the air. Emma sat ",
    l6: "by the window, lost in thought, remembering her last trip to ",
    l7: "the mountains. The fresh air, the sound of rushing streams, and ",
    18: "the smell of pine trees still lingered in her memory. She smiled at",
    l9: "the thought of waking up to the sunrise over snow-covered peaks.",
    l10: "Back in the present, her cat hopped onto her lap and purred softly,",
    l11: "reminding her that even the smallest moments could bring peace.",
    l12: "Maybe, she thought, she didn’t need to travel far to find joy.",
    l13: "Sometimes, it was right here, in the stillness of home, with a warm",
    l14: "drink, a good memory, and a furry companion by her side. The rain",
    l15: "had been falling steadily all morning, tapping gently against the",
    l16: "windows like a calm lullaby. Inside, the house smelled of cinnamon",
    l17: "and fresh-baked cookies, thanks to an early burst of baking inspiration.",
    l18: "The soft hum of music played in the background while Alex curled up",
    l19: "on the couch with a blanket and a favorite movie queued up. Outside,",
    l20: "the street looked like a watercolor painting, with reflections",
    l21: "shimmering on the wet pavement and people walking by with colorful",
    l22: "umbrellas. Even the trees looked more alive, their leaves glistening",
    l23: "with droplets. Alex glanced at the to-do list on the fridge and",
    l24: "smiled, knowing none of it needed attention today. Sometimes the",
    l25: "best kind of productivity was simply taking a break. With a sip of",
    l26: "hot chocolate and the sound of rain as a soundtrack, the world",
    l27: "felt softer, quieter, and just right."
}

/*
let para2 = "Every Saturday morning, Mia and her brother made their way to the local market at the edge of town. The market buzzed with energy: vendors shouting their deals, the smell of fresh flowers and ripe mangoes filling the air, and musicians playing light tunes near the fountain. They always started with the fruit stall where the owner, Mr. Kapoor, handed out samples of juicy oranges with a wink. Next came the bakery stand, where the warmth of fresh bread wrapped around them like a hug. Mia’s favorite part was the tiny bookstall in the corner, where old novels sat beside handmade bookmarks and stories seemed to whisper from worn-out pages. As the sun climbed higher, the crowd grew thicker, but nobody seemed to mind. Everyone had their own rhythm, their own path through the maze of colors and sounds. Late at night, when the world quiets down and the sky turns to velvet, Luna sits by her window and gazes at the stars. They flicker like tiny lanterns, scattered across the dark — each one a whisper of something ancient, something waiting. In the soft stillness, she imagines distant planets with glowing trees, silver oceans, and skies that shift colors with emotion. A breeze drifts in, carrying the scent of jasmine and a promise of dreams yet to come. The moon, round and glowing, watches over her like an old friend. Time feels slower in these hours, like the world is gently holding its breath. She closes her eyes and wonders what it would be like to fly, weightless and free, through those constellations. Maybe there’s a version of her somewhere out there — dancing on Saturn’s rings or collecting stardust in a glass jar. As the night deepens and sleep begins to pull her in, Luna knows that while her feet may stay grounded, her mind can travel as far as the stars will let it."

let para3 = "There’s a place, hidden deep in the folds of a forgotten forest, where dreams go when they’re left behind. The trees there are taller than towers, their leaves shimmering with colors no one can name. Rivers hum lullabies as they flow over glowing stones, and the wind speaks softly, telling stories only the curious can hear. In this forest, time doesn’t follow clocks. Days melt gently into nights, and the sky swirls with soft pastels that stretch endlessly. Birds with feathers like silk sing melodies that echo in the heart long after they’ve passed. Somewhere among the moss and moonlight, you’ll find old dreams resting — dreams of flying, of distant lands, of being someone brave, or wild, or magical. Some sleep quietly under flower-covered blankets, waiting to be remembered. Others dance through the trees like wisps of light, searching for the one who dreamed them. If you ever feel lost, they say this forest finds you. Not with a map or a road, but with a feeling — the sense that something beautiful is just around the corner of your imagination. Imagine a city made of clouds, floating gently above the world like a drifting dream. The buildings are soft and pale, shaped like spun sugar, and the streets are woven with golden light. People move slowly there — not because they have to, but because they want to. Every step feels like gliding. There are sky-trains made of feathers, carousels that spin through sunbeams, and markets where the vendors sell bottled laughter and wishes folded into paper cranes. Time is kind in this place — no rush, no deadlines, just gentle rhythms and quiet moments. On the rooftops, you can lie back and watch the stars blink awake one by one, while the moon smiles as if sharing a secret. Rain, when it comes, falls like soft mist, and umbrellas bloom like flowers. This city doesn’t appear on any map. It can’t be found by searching. But sometimes, in the middle of a nap, or just before waking, you might feel it — a breeze that smells like cotton candy, a lightness in your chest, a sense that you’ve just returned from someplace magical, even if only for a moment."

*/